"""Song detection cascade: P1-P3 rules run on a full :class:`TrackMetadata`.

Pass C only downloads audio for items the pipeline classifies as a song. The
classification is a small cascade of cheap string/regex checks, ordered from
the most authoritative (the YouTube ``Music`` category) to the most permissive
(the auto-generated footer that Art Tracks always carry). The first rule that
fires wins; items that match none are skipped and pass C drops them.

The cascade is implemented as pure functions: no I/O, no globals, no side
effects. That keeps the rule list easy to unit-test and easy to extend (drop
another :func:`_check_*` in front of the return statement and the tests stay
green).
"""

import re
from typing import Final

from taste_pipeline.metadata import TrackMetadata

_RULE_P1: Final[str] = "P1"
_RULE_P2: Final[str] = "P2"
_RULE_P3: Final[str] = "P3"
_RULE_NONE: Final[str] = "none"

_MUSIC_CATEGORY: Final[str] = "music"
_TOPIC_SUFFIX: Final[re.Pattern[str]] = re.compile(r"\s-\sTopic$")
_AUTO_GENERATED_FOOTER: Final[str] = "Auto-generated by YouTube."


def _has_music_category(meta: TrackMetadata) -> bool:
    """Return True when ``meta.categories`` contains ``"Music"`` (case-insensitive, None-safe)."""
    if not meta.categories:
        return False
    return any(category.casefold() == _MUSIC_CATEGORY for category in meta.categories)


def _has_topic_uploader(meta: TrackMetadata) -> bool:
    """Return True when ``meta.uploader`` ends with ``... - Topic`` (None-safe)."""
    uploader = meta.uploader
    if not uploader:
        return False
    return _TOPIC_SUFFIX.search(uploader) is not None


def _has_auto_generated_footer(meta: TrackMetadata) -> bool:
    """Return True when stripped ``meta.description`` ends with the auto-generated footer (None-safe)."""
    description = meta.description
    if not description:
        return False
    return description.strip().endswith(_AUTO_GENERATED_FOOTER)


def is_song(meta: TrackMetadata) -> tuple[bool, str]:
    """Classify a :class:`TrackMetadata` as a song using the P1-P3 cascade.

    The rules run in order P1 -> P2 -> P3. The first rule that matches wins
    and its id (``"P1"``, ``"P2"``, or ``"P3"``) is returned alongside
    ``True``. Items that match no rule are not songs and the rule id is
    ``"none"``.

    Args:
        meta: Normalized full metadata from pass B.

    Returns:
        ``(True, rule_id)`` when at least one rule matched, otherwise
        ``(False, "none")``.
    """
    if _has_music_category(meta):
        return True, _RULE_P1
    if _has_topic_uploader(meta):
        return True, _RULE_P2
    if _has_auto_generated_footer(meta):
        return True, _RULE_P3
    return False, _RULE_NONE
