"""Tests for taste_pipeline.download: FLAC pass-C, metadata sidecars, download-archive, state."""

import json
import logging
import sqlite3
from collections.abc import Iterator, Mapping
from pathlib import Path
from typing import cast

import pytest
from yt_dlp import YoutubeDL
from yt_dlp.utils import DownloadError

from taste_pipeline import download as download_module
from taste_pipeline import feed as feed_module
from taste_pipeline import metadata as metadata_module
from taste_pipeline.config import Config
from taste_pipeline.download import DownloadedTrack, download_songs
from taste_pipeline.metadata import TrackMetadata, metadata_from_json
from taste_pipeline.state import StateStore

SONG_A_ID = "songA0000001"
SONG_B_ID = "songB0000002"
DEAD_ID = "dead0000001"


def _candidate(video_id: str) -> TrackMetadata:
    """Build a song-shaped candidate; the downloader only needs the id, the sidecar needs it all."""
    return TrackMetadata(
        video_id=video_id,
        title="Fake Title",
        uploader="Fake Artist - Topic",
        uploader_id="@fake-artist",
        channel_id="UC3333333333333333333333",
        upload_date="20240115",
        timestamp=1705276800,
        categories=["Music"],
        duration=187.0,
        description="Fake description\nAuto-generated by YouTube.",
        track="Fake Title",
        artist="Fake Artist",
        album="Fake Album",
        thumbnail_url=f"https://i.ytimg.com/vi/{video_id}/maxresdefault.jpg",
        webpage_url=f"https://www.youtube.com/watch?v={video_id}",
    )


def _patch_downloader(
    monkeypatch: pytest.MonkeyPatch, failing_ids: set[str] | None = None
) -> list[dict[str, object]]:
    """Fake ``YoutubeDL.download``: drop a fake FLAC into the outtmpl's inbox; return captured params."""
    failures = failing_ids or set()
    captured: list[dict[str, object]] = []

    def fake_download(self: YoutubeDL, urls: list[str]) -> int:
        captured.append(dict(self.params))
        raw_outtmpl = self.params.get("outtmpl")
        # YoutubeDL.__init__ normalizes a plain-string outtmpl into {"default": outtmpl}.
        template = raw_outtmpl.get("default") if isinstance(raw_outtmpl, dict) else raw_outtmpl
        outtmpl = Path(str(template))
        outtmpl.parent.mkdir(parents=True, exist_ok=True)
        for url in urls:
            video_id = url.rsplit("=", maxsplit=1)[-1]
            if video_id in failures:
                message = "Video unavailable"
                raise DownloadError(message)
            target = outtmpl.parent / f"Fake Artist - Topic - Fake Title [{video_id}].flac"
            _ = target.write_bytes(b"fLaC\x00fake")
        return 0

    monkeypatch.setattr(YoutubeDL, "download", fake_download)
    return captured


def _read_downloads(db_path: Path) -> dict[str, tuple[str, str]]:
    """Return ``video_id -> (stage, audio_path)`` straight from the downloads table."""
    with sqlite3.connect(db_path) as conn:
        rows = cast(
            "list[tuple[str, str, str]]",
            conn.execute("SELECT video_id, stage, audio_path FROM downloads").fetchall(),
        )
    return {row[0]: (row[1], row[2]) for row in rows}


def _read_seen_stages(db_path: Path) -> dict[str, str]:
    """Return ``video_id -> stage`` straight from the seen table."""
    with sqlite3.connect(db_path) as conn:
        rows = cast("list[tuple[str, str]]", conn.execute("SELECT video_id, stage FROM seen").fetchall())
    return {row[0]: row[1] for row in rows}


def _sidecar_for(audio_path: Path) -> Path:
    """The sidecar path pass C writes next to ``audio_path``."""
    return audio_path.with_name(audio_path.name + ".meta.json")


@pytest.fixture
def config(tmp_path: Path) -> Config:
    data_dir = tmp_path / "data"
    return Config(
        like_library_dir=tmp_path,
        data_dir=data_dir,
        cookie_file=tmp_path / "cookies.txt",
        download_archive=data_dir / "yt-dlp-archive.txt",
    )


@pytest.fixture
def state(config: Config) -> Iterator[StateStore]:
    store = StateStore(config.data_dir)
    yield store
    store.close()


def test_download_songs_produces_flacs_sidecars_and_state_rows(
    monkeypatch: pytest.MonkeyPatch, config: Config, state: StateStore
) -> None:
    # Given two song candidates and a fake downloader that drops FLACs into the inbox
    _ = _patch_downloader(monkeypatch)
    candidates = [_candidate(SONG_A_ID), _candidate(SONG_B_ID)]

    # When downloading both
    tracks = download_songs(candidates, config, state)

    # Then both FLACs exist in the inbox, tagged with the video id
    inbox = config.data_dir / "inbox"
    assert len(tracks) == 2
    assert all(isinstance(track, DownloadedTrack) for track in tracks)
    assert [track.meta.video_id for track in tracks] == [SONG_A_ID, SONG_B_ID]
    for track in tracks:
        assert track.audio_path.parent == inbox
        assert track.audio_path.suffix == ".flac"
        assert track.audio_path.is_file()
        assert f"[{track.meta.video_id}]" in track.audio_path.name
        # And each FLAC has its metadata sidecar next to it
        assert _sidecar_for(track.audio_path).is_file()

    # And the downloads table records both ids with stage 'downloaded' and the audio path
    downloads = _read_downloads(state.db_path)
    assert set(downloads) == {SONG_A_ID, SONG_B_ID}
    for track in tracks:
        stage, audio_path = downloads[track.meta.video_id]
        assert stage == "downloaded"
        assert Path(audio_path) == track.audio_path

    # And the seen-history marks both ids as downloaded too
    assert _read_seen_stages(state.db_path) == {SONG_A_ID: "downloaded", SONG_B_ID: "downloaded"}


def test_download_songs_configures_yt_dlp_for_flac_download(
    monkeypatch: pytest.MonkeyPatch, config: Config, state: StateStore
) -> None:
    # Given the fake downloader capturing the params YoutubeDL was built with
    captured = _patch_downloader(monkeypatch)

    # When downloading one candidate
    _ = download_songs([_candidate(SONG_A_ID)], config, state)

    # Then yt-dlp is configured for FLAC audio extraction into the inbox with the archive
    assert len(captured) == 1
    params = captured[0]
    assert params["format"] == "bestaudio/best"
    assert params["cookiefile"] == str(config.cookie_file)
    assert "inbox" in str(params["outtmpl"])
    assert params["postprocessors"] == [{"key": "FFmpegExtractAudio", "preferredcodec": "flac"}]
    assert params["download_archive"] == str(config.download_archive)
    assert params["quiet"] is True
    assert params["noprogress"] is True
    # Guardrails: pass C downloads for real — no read-only or flat-listing flags
    assert "skip_download" not in params
    assert "extract_flat" not in params


def test_download_songs_sidecar_round_trips_to_equal_metadata(
    monkeypatch: pytest.MonkeyPatch, config: Config, state: StateStore
) -> None:
    # Given a downloaded candidate
    _ = _patch_downloader(monkeypatch)
    candidate = _candidate(SONG_A_ID)
    tracks = download_songs([candidate], config, state)

    # When reading the sidecar back through a real json cycle
    sidecar = _sidecar_for(tracks[0].audio_path)
    raw = cast("Mapping[str, object]", json.loads(sidecar.read_text(encoding="utf-8")))
    rebuilt = metadata_from_json(raw)

    # Then the rebuilt metadata equals the candidate that produced it
    assert rebuilt == candidate
    assert isinstance(rebuilt, TrackMetadata)


def test_download_songs_skips_failed_video_and_continues(
    monkeypatch: pytest.MonkeyPatch,
    config: Config,
    state: StateStore,
    caplog: pytest.LogCaptureFixture,
) -> None:
    # Given three candidates of which the first one fails in yt-dlp
    _ = _patch_downloader(monkeypatch, failing_ids={DEAD_ID})
    candidates = [_candidate(DEAD_ID), _candidate(SONG_A_ID), _candidate(SONG_B_ID)]

    # When downloading with logging captured
    with caplog.at_level(logging.WARNING, logger="taste_pipeline.download"):
        tracks = download_songs(candidates, config, state)

    # Then the two live videos are downloaded, no exception escapes, and the failure is logged
    assert [track.meta.video_id for track in tracks] == [SONG_A_ID, SONG_B_ID]
    assert any(DEAD_ID in record.message for record in caplog.records)
    assert set(_read_downloads(state.db_path)) == {SONG_A_ID, SONG_B_ID}
    inbox = config.data_dir / "inbox"
    assert not [path for path in inbox.iterdir() if DEAD_ID in path.name]


def test_ydl_options_thread_the_proxy_into_every_call_site(tmp_path: Path) -> None:
    # Given a config with a proxy (blocked regions route yt-dlp through one)
    config = Config(
        like_library_dir=tmp_path,
        data_dir=tmp_path / "data",
        cookie_file=tmp_path / "cookies.txt",
        download_archive=tmp_path / "data" / "yt-dlp-archive.txt",
        proxy="http://127.0.0.1:56551",
    )

    # Then feed, metadata and download all pass the proxy through to yt-dlp
    assert download_module._ydl_options(config)["proxy"] == "http://127.0.0.1:56551"
    assert feed_module._ydl_options(config)["proxy"] == "http://127.0.0.1:56551"
    assert metadata_module._ydl_options(config)["proxy"] == "http://127.0.0.1:56551"
