"""Tests for taste_pipeline.metadata: bounded pass-B fetch, normalization, JSON round-trip."""

import dataclasses
import json
import logging
import sqlite3
from collections.abc import Iterator, Mapping
from pathlib import Path
from typing import cast

import pytest
from yt_dlp import YoutubeDL
from yt_dlp.utils import DownloadError

from taste_pipeline.config import Config
from taste_pipeline.metadata import (
    TrackMetadata,
    fetch_metadata,
    metadata_from_json,
    metadata_to_json,
)
from taste_pipeline.state import StateStore

FIXTURE_DIR = Path(__file__).parent / "fixtures"
SONG_FIXTURE = FIXTURE_DIR / "full_meta_song.json"
TALK_FIXTURE = FIXTURE_DIR / "full_meta_talk.json"
SONG_ID = "song0000001"
TALK_ID = "talk0000001"


def _load_fixture(path: Path) -> dict[str, object]:
    """Load a recorded full info dict; json.loads is the untyped boundary."""
    return cast("dict[str, object]", json.loads(path.read_text(encoding="utf-8")))


def _patch_extractor(
    monkeypatch: pytest.MonkeyPatch, by_id: Mapping[str, dict[str, object]]
) -> list[dict[str, object]]:
    """Replay fixture info dicts through a fake extractor; return captured YoutubeDL params."""
    captured: list[dict[str, object]] = []

    def fake_extract_info(self: YoutubeDL, url: str, *, download: bool = False) -> dict[str, object]:
        _ = download
        captured.append(dict(self.params))
        video_id = url.rsplit("=", maxsplit=1)[-1]
        return by_id[video_id]

    monkeypatch.setattr(YoutubeDL, "extract_info", fake_extract_info)
    return captured


def _patch_flaky_extractor(
    monkeypatch: pytest.MonkeyPatch, by_id: Mapping[str, dict[str, object]], failing_ids: set[str]
) -> None:
    """Fake extractor raising ``DownloadError`` for ``failing_ids`` like a deleted/private video."""
    unavailable = "Video unavailable"

    def fake_extract_info(self: YoutubeDL, url: str, *, download: bool = False) -> dict[str, object]:
        _ = (self, download)
        video_id = url.rsplit("=", maxsplit=1)[-1]
        if video_id in failing_ids:
            raise DownloadError(unavailable)
        return by_id[video_id]

    monkeypatch.setattr(YoutubeDL, "extract_info", fake_extract_info)


def _default_fixtures() -> dict[str, dict[str, object]]:
    song = _load_fixture(SONG_FIXTURE)
    talk = _load_fixture(TALK_FIXTURE)
    return {SONG_ID: song, TALK_ID: talk}


def _read_stages(db_path: Path) -> dict[str, str]:
    with sqlite3.connect(db_path) as conn:
        rows = conn.execute("SELECT video_id, stage FROM seen").fetchall()
    return {row[0]: row[1] for row in rows}


@pytest.fixture
def config(tmp_path: Path) -> Config:
    data_dir = tmp_path / "data"
    return Config(
        like_library_dir=tmp_path,
        data_dir=data_dir,
        cookie_file=tmp_path / "cookies.txt",
        download_archive=data_dir / "yt-dlp-archive.txt",
        max_metadata_fetch=150,
    )


@pytest.fixture
def state(config: Config) -> Iterator[StateStore]:
    store = StateStore(config.data_dir)
    yield store
    store.close()


def test_fetch_metadata_normalizes_art_track_fields(
    monkeypatch: pytest.MonkeyPatch, config: Config, state: StateStore
) -> None:
    # Given a recorded Art Track info dict replayed through the fake extractor
    _patch_extractor(monkeypatch, _default_fixtures())

    # When fetching metadata for the song id
    results = fetch_metadata([SONG_ID], config, state)

    # Then the Art Track fields are normalized: Music category, track/artist/album
    # present, timestamp as int, duration as float, and the auto-generated footer
    assert len(results) == 1
    meta = results[0]
    assert meta.video_id == SONG_ID
    assert meta.title == "siqlo - Hack and Slash"
    assert meta.uploader == "siqlo - Topic"
    assert meta.uploader_id == "@siqlo-topic"
    assert meta.channel_id == "UC2222222222222222222222"
    assert meta.upload_date == "20240115"
    assert meta.timestamp == 1705276800
    assert meta.categories == ["Music"]
    assert meta.duration == 187.0
    assert isinstance(meta.duration, float)
    assert meta.description is not None
    assert meta.description.endswith("Auto-generated by YouTube.")
    assert meta.track == "Hack and Slash"
    assert meta.artist == "siqlo"
    assert meta.album == "Hack and Slash"
    assert meta.thumbnail_url == "https://i.ytimg.com/vi/song0000001/maxresdefault.jpg"
    assert meta.webpage_url == f"https://www.youtube.com/watch?v={SONG_ID}"


def test_fetch_metadata_normalizes_talk_fields(
    monkeypatch: pytest.MonkeyPatch, config: Config, state: StateStore
) -> None:
    # Given a recorded podcast info dict replayed through the fake extractor
    _patch_extractor(monkeypatch, _default_fixtures())

    # When fetching metadata for the talk id
    results = fetch_metadata([TALK_ID], config, state)

    # Then the podcast has the People & Blogs category and no Art Track fields
    assert len(results) == 1
    meta = results[0]
    assert meta.video_id == TALK_ID
    assert meta.categories == ["People & Blogs"]
    assert meta.track is None
    assert meta.artist is None
    assert meta.album is None
    assert meta.duration == 3600.5


def test_fetch_metadata_preserves_input_order(
    monkeypatch: pytest.MonkeyPatch, config: Config, state: StateStore
) -> None:
    # Given both fixtures available
    _patch_extractor(monkeypatch, _default_fixtures())

    # When fetching in a specific order
    results = fetch_metadata([TALK_ID, SONG_ID], config, state)

    # Then results follow input order
    assert [meta.video_id for meta in results] == [TALK_ID, SONG_ID]


def test_fetch_metadata_enforces_bound_and_logs_deferral(
    monkeypatch: pytest.MonkeyPatch,
    config: Config,
    state: StateStore,
    caplog: pytest.LogCaptureFixture,
) -> None:
    # Given 200 candidate ids and a bound of 3
    _patch_extractor(monkeypatch, _default_fixtures())
    config = dataclasses.replace(config, max_metadata_fetch=3)
    video_ids = [SONG_ID, TALK_ID, SONG_ID] + [f"defer{i:07d}" for i in range(197)]

    # When fetching metadata with logging captured
    with caplog.at_level(logging.INFO, logger="taste_pipeline.metadata"):
        results = fetch_metadata(video_ids, config, state)

    # Then exactly 3 videos were fetched (one per extract call) and 197 deferred
    assert len(results) == 3
    assert any("deferring 197 ids" in record.message for record in caplog.records)


def test_fetch_metadata_skips_deleted_video_and_continues(
    monkeypatch: pytest.MonkeyPatch,
    config: Config,
    state: StateStore,
    caplog: pytest.LogCaptureFixture,
) -> None:
    # Given three ids of which the middle one is deleted
    fixtures = _default_fixtures()
    _patch_flaky_extractor(monkeypatch, fixtures, failing_ids={"dead0000001"})

    # When fetching metadata with logging captured
    with caplog.at_level(logging.WARNING, logger="taste_pipeline.metadata"):
        results = fetch_metadata([SONG_ID, "dead0000001", TALK_ID], config, state)

    # Then the two live videos are returned, no exception escapes, and the skip is logged
    assert [meta.video_id for meta in results] == [SONG_ID, TALK_ID]
    assert any("dead0000001" in record.message for record in caplog.records)


def test_fetch_metadata_records_fetched_ids_as_metadata_stage(
    monkeypatch: pytest.MonkeyPatch, config: Config, state: StateStore
) -> None:
    # Given both fixtures available
    _patch_extractor(monkeypatch, _default_fixtures())

    # When fetching metadata
    _ = fetch_metadata([SONG_ID, TALK_ID], config, state)

    # Then every fetched id is in the seen-history (recorded with stage 'metadata')
    assert state.already_seen(SONG_ID)
    assert state.already_seen(TALK_ID)
    stages = _read_stages(state.db_path)
    assert stages == {SONG_ID: "metadata", TALK_ID: "metadata"}


def test_fetch_metadata_configures_yt_dlp_for_full_readonly_extraction(
    monkeypatch: pytest.MonkeyPatch, config: Config, state: StateStore
) -> None:
    # Given the fake extractor capturing the params YoutubeDL was built with
    captured = _patch_extractor(monkeypatch, _default_fixtures())

    # When fetching metadata for one id
    _ = fetch_metadata([SONG_ID], config, state)

    # Then yt-dlp is configured for a full, read-only, cookie-authenticated extraction
    assert len(captured) == 1
    params = captured[0]
    assert params["skip_download"] is True
    assert params["cookiefile"] == str(config.cookie_file)
    assert params["quiet"] is True
    assert params["no_warnings"] is True
    # Guardrails: pass B must not reuse pass A's flat-listing or download-archive flags
    assert "extract_flat" not in params
    assert "download_archive" not in params


def test_metadata_json_round_trip(
    monkeypatch: pytest.MonkeyPatch, config: Config, state: StateStore
) -> None:
    # Given metadata fetched from the recorded fixtures
    _patch_extractor(monkeypatch, _default_fixtures())
    results = fetch_metadata([SONG_ID, TALK_ID], config, state)

    # When serializing to JSON and back (through a real json.dumps/loads cycle)
    for meta in results:
        raw = json.loads(json.dumps(metadata_to_json(meta)))
        rebuilt = metadata_from_json(cast("Mapping[str, object]", raw))

        # Then the rebuilt value equals the original
        assert rebuilt == meta
        assert isinstance(rebuilt, TrackMetadata)
