"""Tests for taste_pipeline.detect: P1-P3 song detection cascade."""

import json
from pathlib import Path
from typing import cast

from taste_pipeline.detect import is_song
from taste_pipeline.metadata import TrackMetadata

FIXTURE_DIR = Path(__file__).parent / "fixtures"
SONG_FIXTURE = FIXTURE_DIR / "full_meta_song.json"
TALK_FIXTURE = FIXTURE_DIR / "full_meta_talk.json"


def _load_info_dict(path: Path) -> dict[str, object]:
    """Load a recorded full yt-dlp info dict; json.loads is the untyped boundary."""
    return cast("dict[str, object]", json.loads(path.read_text(encoding="utf-8")))


def _fixture_to_metadata(path: Path) -> TrackMetadata:
    """Normalize a recorded info dict into a :class:`TrackMetadata` (mirrors pass-B normalization)."""
    info = _load_info_dict(path)

    def _opt_str(key: str) -> str | None:
        value = info.get(key)
        return value if isinstance(value, str) else None

    def _opt_int(key: str) -> int | None:
        value = info.get(key)
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            return None
        return int(value)

    def _opt_float(key: str) -> float | None:
        value = info.get(key)
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            return None
        return float(value)

    def _opt_str_list(key: str) -> list[str] | None:
        value = info.get(key)
        if not isinstance(value, list):
            return None
        return [item for item in value if isinstance(item, str)]

    return TrackMetadata(
        video_id=_opt_str("id") or "",
        title=_opt_str("title"),
        uploader=_opt_str("uploader"),
        uploader_id=_opt_str("uploader_id"),
        channel_id=_opt_str("channel_id"),
        upload_date=_opt_str("upload_date"),
        timestamp=_opt_int("timestamp"),
        categories=_opt_str_list("categories"),
        duration=_opt_float("duration"),
        description=_opt_str("description"),
        track=_opt_str("track"),
        artist=_opt_str("artist"),
        album=_opt_str("album"),
        thumbnail_url=_opt_str("thumbnail"),
        webpage_url=_opt_str("webpage_url"),
    )


def _make_meta(
    *,
    categories: list[str] | None = None,
    uploader: str | None = None,
    description: str | None = None,
) -> TrackMetadata:
    """Build a :class:`TrackMetadata` with only the cascade-relevant fields populated."""
    return TrackMetadata(
        video_id="vid0000001",
        title=None,
        uploader=uploader,
        uploader_id=None,
        channel_id=None,
        upload_date=None,
        timestamp=None,
        categories=categories,
        duration=None,
        description=description,
        track=None,
        artist=None,
        album=None,
        thumbnail_url=None,
        webpage_url=None,
    )


# ── P1: Music category ────────────────────────────────────────────────────


def test_p1_fires_when_music_category_present() -> None:
    # Given a metadata with the Music category
    meta = _make_meta(categories=["Music"])

    # When classifying
    is_song_result, rule = is_song(meta)

    # Then P1 wins
    assert is_song_result is True
    assert rule == "P1"


def test_p1_is_case_insensitive() -> None:
    # Given the Music category spelled in different cases
    meta = _make_meta(categories=["music", "MUSIC"])

    # When classifying
    is_song_result, rule = is_song(meta)

    # Then P1 still wins
    assert is_song_result is True
    assert rule == "P1"


# ── P2: ... - Topic uploader ──────────────────────────────────────────────


def test_p2_fires_when_uploader_is_topic_with_non_music_category() -> None:
    # Given a Topic uploader and a non-Music category
    meta = _make_meta(
        categories=["People & Blogs"],
        uploader="Veorra - Topic",
        description="no footer here",
    )

    # When classifying
    is_song_result, rule = is_song(meta)

    # Then P2 wins (and P1/P3 do not)
    assert is_song_result is True
    assert rule == "P2"


def test_p2_fires_before_p3_when_both_match() -> None:
    # Given a Topic uploader AND an auto-generated footer; categories miss P1
    meta = _make_meta(
        categories=["Entertainment"],
        uploader="Some Artist - Topic",
        description="Track listing\n\nAuto-generated by YouTube.",
    )

    # When classifying
    is_song_result, rule = is_song(meta)

    # Then P2 wins because the cascade short-circuits before P3
    assert is_song_result is True
    assert rule == "P2"


# ── P3: Auto-generated footer ─────────────────────────────────────────────


def test_p3_fires_when_only_footer_matches() -> None:
    # Given a description ending with the auto-generated footer; no Music, no Topic
    meta = _make_meta(
        categories=["Entertainment"],
        uploader="Some Uploader",
        description="Track listing\n\nAuto-generated by YouTube.",
    )

    # When classifying
    is_song_result, rule = is_song(meta)

    # Then P3 wins
    assert is_song_result is True
    assert rule == "P3"


def test_p3_strips_trailing_whitespace_before_matching() -> None:
    # Given a description that ends with the footer followed by trailing newlines
    meta = _make_meta(
        categories=["Entertainment"],
        uploader="Some Uploader",
        description="Auto-generated by YouTube.\n\n",
    )

    # When classifying
    is_song_result, rule = is_song(meta)

    # Then P3 still wins because the description is stripped before the suffix check
    assert is_song_result is True
    assert rule == "P3"


# ── Negative paths ────────────────────────────────────────────────────────


def test_returns_none_for_all_none_metadata() -> None:
    # Given a metadata with every cascade-relevant field None
    meta = _make_meta()

    # When classifying
    is_song_result, rule = is_song(meta)

    # Then nothing matches and the rule id is the literal "none"
    assert is_song_result is False
    assert rule == "none"


def test_talk_fixture_is_not_a_song() -> None:
    # Given the recorded podcast info dict from the test fixtures
    meta = _fixture_to_metadata(TALK_FIXTURE)

    # When classifying
    is_song_result, rule = is_song(meta)

    # Then the podcast is not classified as a song
    assert is_song_result is False
    assert rule == "none"


def test_song_fixture_classifies_as_p1() -> None:
    # Given the recorded Art Track info dict (matches P1, P2, and P3 simultaneously)
    meta = _fixture_to_metadata(SONG_FIXTURE)

    # When classifying
    is_song_result, rule = is_song(meta)

    # Then P1 wins because it is the highest-priority rule in the cascade
    assert is_song_result is True
    assert rule == "P1"
